### ISSUE TITLE
uninstall command remove /usr/bin 

### ISSUE THREAD

**Issue by Anatole2409** [txoof/slimpi_epd#3]
When running ./install.sh --uninstall, the script remove the directory /usr/bin 

the source : 
`rm -r $installPath`

should be
`rm -r $installPath/$appName`

**Comment by txoof** [comment]
@Anatole2409  Thank you for this!

My sincere apologies and I hope this didn't cause you too many problems.

**Comment by Anatole2409** [comment]
No, thanks, it was at the beginning... I am trying to run slimpi on a raspberry pi 3 ... 
unfortunatly it is not working. 
Trying to rebuild.... not good, slimpi need python 3.7 and I have python 3.5 .

**Comment by txoof** [comment]
You should not need to build it; the tar contains an "executable" version created with pyinstaller. What specific problems are you having building it?

If you do want to rebuild it, you can use pyenv and pipenv to create a build environment that has the necessary components. 

Here are some pretty decent [instructions for installing pyenv](https://realpython.com/intro-to-pyenv/). 

From there, you should be able to install a 3.7 environment and then install pipenv.

Finally, switch to the source directory and run `$ pipenv sync` to create an compatible build environment.

You can also *try* to edit the `Pipfile` and switch the minimum required version to 3.5. I have a feeling that will fail spectacularly though.

**Comment by txoof** [comment]
I've opened a new ticket here: https://github.com/txoof/slimpi_epd/issues/5

Feel free to add your issues; I'm curious to see what problems you're having
