### ISSUE TITLE
Error with Waveshare 3-color display

### ISSUE THREAD

**Issue by tmmorin** [txoof/slimpi_epd#4]
I have a waveshare 3-color 7.5" display.

I tried `display=epd7in5bc_V2` which seems to be the 3-color variant.
But I get the following error:
```
22:23:30 Screen:initEPD:310:INFO - <waveshare_epd.epd7in5bc.EPD object at 0xb5453bb0> initialized
22:23:32 Screen:writeEPD:350:ERROR - failed to write to epd: display() missing 1 required positional argument: 'imagered'
```
I'm guessing that the code is possibly not ready for 3-color displays...?

The non-"bc" variant give a result that shows some stuff but seems buggy, wrong lines, flicker, etc.

(Thanks for pushing this great project on github, I hope I'll be successful in using it ! :+1: )

**Comment by txoof** [comment]
Indeed, the BC variant expects an additional parameter when writing to the display. I'll remove the bc versions from the documentation; you should be able to use the similar monochrome version in the configuration. 

When you say you get buggy output, can you share photo of the screen? I had some terrible results  with banding and partial refreshes when I plugged the hat into the GPIO headers. I switched to using the JST plug with dupont connectors directly to just the pins I needed and it completely resolved the quality issues. You can see some [examples here](https://hackaday.io/project/170051-slimpi).

**EDIT: better link for banding issues:** [banding issue](https://hackaday.io/project/170051/gallery#e210d49255182cca6dcef99cc84ba1d1)

I'll look into what needs to be done to update the drawing libraries to support the color screens. It looks like it's going to be a bit of a project though. https://github.com/txoof/epdlib/issues/1

**Comment by txoof** [comment]
@tmmorin It actually looks a lot easier to fix than I thought. I'll need to do some hacking around on the epdlibrary side to make this work, but it should be a pretty easy fix.

I should be able to have a fix sometime this week. 

Can you share some images of the "buggy" output?

**Comment by tmmorin** [comment]
Hi @txoof 

I found a solution: https://github.com/txoof/epdlib/pull/2 (perhaps close to what you had in mind ?)

The buggy output I had with the epd7in5_V2.py (without "bc") was that after displaying properly the picture, during the "e-Paper busy" waiting, the picture started to kind of fade step by step towards a finally fully white display.  It seems that it's possibly because my display just would not support being driven by a driver that uses only the commands for a single display...

Now I have something that works nicely :smiley: 
The display refresh time is a bit longer than I would have hoped (pushing the red image additionally take a bit more time), and the driver busy loop eats a lot of CPU (the `while true`  without a sleep, in waveshare driver code, is quite violent...).

**Comment by txoof** [comment]
I'm so glad you have a working solution! Thanks for your work on this. You and I landed about the same place, but with slightly different approaches. 

Those waveshare libraries are a piece of work with some really nasty "features".

I'll look into merging in your suggestion once I fix my build tool-chain. Some updates did a great job of breaking things. I should know better than to update stuff.

**Comment by txoof** [comment]
I'll test out the development version of epdlib against slimpi and finally build a new installable in the next day or so.

**Comment by txoof** [comment]
New epdlib version corrects this: https://github.com/txoof/epdlib/commit/747fb57a754be1c22bb45535cfba3ed48c468cd2

**Comment by tmmorin** [comment]
Thanks!

**Comment by txoof** [comment]
@tmmorin my pleasure. I'd love to know if it's working for you and see a pic if you don't mind sharing.

**Comment by tmmorin** [comment]
Yes, sorry for being too implicit: it works and allows me to use slimpi with my waveshare 3-color screen.

I'll send a picture when I have something a bit nice to show.
I plan to have the ribbon cable at the top of my display. I'm working on small changes to rotate images by 180 degrees to compensate for that.

**Comment by txoof** [comment]
Ohh. That would be a great feature to add to the configuration; I'd love to collaborate with you on this.

**Comment by txoof** [comment]
@tmmorin I opened a new issue here #7 with some thoughts on what needs to be updated
